export const HISTORY_TERMINOLOGY = {
  universeName: "历史",
  enterButton: "进入历史",
  selectionTitle: "选择执政基调",
  scenarioHintTitle: "设定愿景",
  scenarioHintDescription:
    "您可以描述期望的文明、年代、身份和大致剧情，AI将重点参考您的愿景生成剧本。留空则由AI随机生成。",
  scenarioHintPlaceholder: "例如：战国末期秦国、大航海时代的葡萄牙...",
  startButton: "开始推演",
  cancelButton: "取消",

  chronicleLabel: "编年史",
  cabinetLabel: "内阁",
  courtDebateLabel: "廷议",
  intelligenceLabel: "情报",

  advisorLabel: "顾问",
  advisorRoles: {
    General: "将军",
    Diplomat: "外交官",
    Intel: "密探",
    Scholar: "学者",
    Merchant: "商人",
  } as const,

  statLabels: {
    stability: "稳定性",
    economy: "经济",
    military: "军事",
    international_standing: "国际声望",
  } as const,
  statAriaLabel: "国家属性",

  chroniclePrompt: "阁下，作为{title}，您的第一道政令是什么？",
  courtDebatePrompt: "{title}，可在朝堂上提出议题，令群臣廷议",
  inputPlaceholder: "下达指令...（外交、经济、军事等）",
  counselLabel: "密谈",
  counselPrivateLabel: "私下密谈",
  counselAskPrompt: "向{name}提出你的问题",
  counselPrivateHint: "此番对话仅你与{name}知晓",
  counselInputPlaceholder: "向{name}提问...",
  counselWhispering: "{name}正在低语...",
  counselError: "问对失败",

  crisisLabel: "当前危机",
  rumorLabel: "民间传言：",
  historianLabel: "史官注疏",
  intelLabel: "最新情报",
  identityChangeLabel: "身份变更",
  loadingText: "推演中...",

  endGameTitle: "结束推演",
  endGameConfirm: "确定要结束本次推演吗？",
  endGameEarlyHint: "当前局势尚未明朗，建议继续推演以获得更完整的结局。",
  endGameEarlyConfirm: "当前第{turn}回合，历史仍在书写中。确定要提前结束吗？",
  endGameNormalConfirm: "当前第{turn}回合，将生成终局分析报告。",
  endGameTurnSummary: "历经 {turn} 回合 · 综合评分 {score}",
  continueButton: "继续推演",
  confirmEndButton: "确认结束",
  personaLabel: "统治者画像",
  realHistoryLabel: "真实历史：",
  historyResultLabel: "历史结果：",
  yourResultLabel: "你的结果：",
  modernEchoLabel: "历史余响",
  alternativeHistoryLabel: "平行历史演化",
  comparisonLabel: "对比分析",
  similarFigureLabel: "相似历史人物：",
  rulerPortraitLabel: "统治者画像",
  dimensionLabels: {
    Authority: "权威",
    Strategy: "战略",
    Empathy: "共情",
    Vision: "远见",
    Economy: "经济",
  } as const,
  decisionReviewLabel: "决策复盘",
  playAgainButton: "再来一局",
  backToHomeButton: "返回主页",

  outcomeLabels: { victory: "胜利", neutral: "存续", defeat: "失败" } as const,

  attitudeLabels: {
    hostile: "敌对",
    peace: "求和",
    neutral: "中立",
    friendly: "友好",
    vassal: "臣服",
    destroyed: "已灭亡",
  } as const,

  attitudeFallbackMap: {
    即将归附: "vassal",
    倾向臣服: "vassal",
    即将臣服: "vassal",
    表面臣服: "vassal",
    归附: "vassal",
    归顺: "vassal",
    降服: "vassal",
    倾向敌对: "hostile",
    敌视: "hostile",
    仇恨: "hostile",
    敌意: "hostile",
    亲近: "friendly",
    友善: "friendly",
    亲善: "friendly",
    和平: "peace",
    议和: "peace",
    示好: "peace",
    冷淡: "neutral",
    疏远: "neutral",
    观望: "neutral",
  } as const,

  factionNewLabel: "● 新势力出现",
  factionStrengthLabel: "优势：",
  factionWeaknessLabel: "弱点：",
  factionNeedsLabel: "急需：",

  leaderStatusLabels: {
    active: "在世",
    dead: "已故",
    exiled: "已流放",
    overthrown: "已推翻",
  } as const,
  advisorStatusLabels: {
    active: "在任",
    dead: "已故",
    exiled: "已流放",
    retired: "已致仕",
  } as const,

  stanceLabels: {
    support: "支持",
    oppose: "驳斥",
    supplement: "补充",
  } as const,

  debateEmptyPrompt: "{title}，可在朝堂上提出议题，令群臣廷议",
  debateResultHint: "廷议结果仅供决策参考",
  debateDiscussing: "群臣商议中...",
  debatePreparing: "群臣准备陈词...",
  debateFinished: "廷议已结束 · 共{rounds}轮",
  debateInProgress: "廷议进行中 · 第{current}/{total}轮",
  debateInProgressShort: "廷议进行中...",
  debateInputPlaceholder: "提出议题...",
  debateSubmitLabel: "发起廷议",
  debateError: "廷议失败",

  radarLabels: ["权威", "战略", "共情", "远见", "经济"] as const,

  defaultNationName: "未知国家",
  defaultLeaderTitle: "统治者",
  defaultScenarioTitle: "未知剧本",
  defaultStyleName: "自定义剧本",

  backButton: "返回主页",
  saveButton: "存档",

  gamePanelAriaLabel: "游戏面板",
  sidebarAriaLabel: "侧边栏",

  evaluateError: "推演失败",
  jsonParseError: "AI 返回格式异常，请检查 API 配置或更换模型",
  endGameError: "结束推演失败",
} as const;
