export const LIFE_TERMINOLOGY = {
  universeName: "人生",
  enterButton: "进入人生",
  selectionTitle: "选择人生轨迹",
  scenarioHintTitle: "设定愿景",
  scenarioHintDescription:
    "您可以描述期望的时代、身份和际遇，AI将重点参考您的愿景生成剧本。留空则由AI随机生成。",
  scenarioHintPlaceholder: "例如：明朝中叶七品县令、罗马帝国行省总督...",
  startButton: "开始仕途",
  cancelButton: "取消",

  chronicleLabel: "履历",
  cabinetLabel: "幕僚",
  courtDebateLabel: "议事",
  intelligenceLabel: "风声",

  sandTableLabel: "棋局",
  sandTableTurnLabel: "棋局",
  sandTableEmptyLabel: "棋局布阵中",
  sandTableEmptyHint: "正在推演各方势力...",
  sandTableUpdatingLabel: "推演中...",
  sandTablePlayerLabel: "我",

  advisorLabel: "同僚",
  advisorRoles: {
    General: "武官",
    Diplomat: "礼官",
    Intel: "暗探",
    Scholar: "文官",
    Merchant: "商贾",
  } as const,

  statLabels: {
    stability: "威望",
    economy: "财力",
    military: "权势",
    international_standing: "圣眷",
  } as const,
  statAriaLabel: "仕途属性",

  chroniclePrompt: "{honorific_prefix}，身为{title}，您打算如何行事？",
  courtDebatePrompt: "{title}，可提出议题，与{ministers_term}议事",
  inputPlaceholder: "上书言事...（奏请、结交、上表等）",
  counselLabel: "私议",
  counselPrivateLabel: "私下密议",
  counselAskPrompt: "向{name}请教",
  counselPrivateHint: "此番对话仅你与{name}知晓",
  counselInputPlaceholder: "向{name}请教...",
  counselWhispering: "{name}正在低语...",
  counselError: "私议失败",

  crisisLabel: "当务之急",
  rumorLabel: "坊间传闻：",
  historianLabel: "同僚评语",
  intelLabel: "最新动向",
  identityChangeLabel: "品秩变动",
  loadingText: "演绎中...",

  endGameTitle: "致仕",
  endGameLockedHint: "第8回合后方可致仕",
  endGameConfirm: "确定要结束本次仕途吗？",
  endGameEarlyHint: "仕途方才起步，建议继续为官以获得更完整的结局。",
  endGameEarlyConfirm: "当前第{turn}回合，仕途仍在继续。确定要提前致仕吗？",
  endGameNormalConfirm: "当前第{turn}回合，将生成仕途总结报告。",
  endGameTurnSummary: "历经 {turn} 回合 · 综合评分 {score}",
  continueButton: "继续为官",
  confirmEndButton: "确认致仕",
  personaLabel: "仕途画像",
  realHistoryLabel: "真实历史：",
  historyResultLabel: "历史结果：",
  yourResultLabel: "你的结局：",
  modernEchoLabel: "历史余响",
  alternativeHistoryLabel: "平行命运演化",
  comparisonLabel: "对比分析",
  similarFigureLabel: "相似历史人物：",
  rulerPortraitLabel: "角色画像",
  dimensionLabels: {
    Authority: "权谋",
    Strategy: "手腕",
    Empathy: "人脉",
    Vision: "远见",
    Economy: "家底",
  } as const,
  decisionReviewLabel: "仕途复盘",
  playAgainButton: "再入仕途",
  backToHomeButton: "返回主页",

  outcomeLabels: {
    victory: "功成",
    neutral: "浮沉",
    defeat: "落魄",
  } as const,

  attitudeLabels: {
    hostile: "打压",
    peace: "利用",
    neutral: "观望",
    friendly: "提携",
    vassal: "依附",
    destroyed: "覆灭",
  } as const,

  attitudeFallbackMap: {
    忌惮: "hostile",
    排挤: "hostile",
    压制: "hostile",
    拉拢: "friendly",
    扶持: "friendly",
    提携: "friendly",
    勾结: "peace",
    妥协: "peace",
    利益交换: "peace",
    冷眼: "neutral",
    旁观: "neutral",
    观望: "neutral",
    附庸: "vassal",
    依附: "vassal",
    效忠: "vassal",
  } as const,

  factionNewLabel: "● 新势力浮现",
  factionStrengthLabel: "优势：",
  factionWeaknessLabel: "软肋：",
  factionNeedsLabel: "所求：",

  superiorLabel: "上位者：",
  superiorAttitudeLabels: {
    trust: "信任重用",
    normal: "正常看待",
    wary: "猜忌防范",
    danger: "随时被贬",
    fatal: "命悬一线",
  } as const,

  leaderStatusLabels: {
    active: "在位",
    dead: "已故",
    exiled: "已流放",
    overthrown: "已罢免",
  } as const,
  advisorStatusLabels: {
    active: "在任",
    dead: "已故",
    exiled: "已流放",
    retired: "已致仕",
  } as const,

  stanceLabels: {
    support: "附议",
    oppose: "驳斥",
    supplement: "补充",
  } as const,

  debateEmptyPrompt: "{title}，可提出议题，与{ministers_term}议事",
  debateResultHint: "议事结果仅供决策参考",
  debateDiscussing: "{ministers_term}商议中...",
  debatePreparing: "{ministers_term}准备发言...",
  debateFinished: "议事已结束 · 共{rounds}轮",
  debateInProgress: "议事进行中 · 第{current}/{total}轮",
  debateInProgressShort: "议事进行中...",
  debateInputPlaceholder: "提出议题...",
  debateSubmitLabel: "发起议事",
  debateError: "议事失败",

  radarLabels: ["权谋", "手腕", "人脉", "远见", "家底"] as const,

  defaultNationName: "未知衙门",
  defaultLeaderTitle: "大人",
  defaultLeaderLabel: "大人",
  defaultCourtTerm: "议事厅",
  defaultMinistersTerm: "同僚",
  defaultHonorificPrefix: "大人",
  defaultScenarioTitle: "未知仕途",
  defaultStyleName: "自定义仕途",

  backButton: "返回主页",
  saveButton: "存档",

  gamePanelAriaLabel: "仕途面板",
  sidebarAriaLabel: "侧边栏",

  evaluateError: "演绎失败",
  jsonParseError: "AI 返回格式异常，请检查 API 配置或更换模型",
  endGameError: "致仕失败",

  tendencyLabel: "倾向：",
  hiddenMotiveShow: "查看隐情",
  hiddenMotiveHide: "隐藏隐情",
  settingsLabel: "设置",
  turnLabel: "任期",
  loadingLabel: "加载中...",
  confirmSelectButton: "确认选择",
  decisionSelectTitle: "奏请选择",
  decisionSelectHint: "选择一项或多项奏请方向，确认后将填入输入框",
  recommendSuffix: "荐",
  inputAriaLabel: "奏请输入",
  sendAriaLabel: "发送奏请",
  advisorVacantHint: "此位置将在下回合由新人接替",
  rankLabel: "品级：",
  favorAriaLabel: "圣眷",
} as const;
